[package]
name = "sodg"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/objectionary/sodg"
description = "Surging Object DiGraph (SODG)"
readme = "README.md"
license-file = "LICENSE.txt"
homepage = "https://github.com/objectionary/sodg"
keywords = ["graph", "oop"]
categories = ["data-structures", "memory-management"]

[features]
gc = []

[dependencies]
tinymap = "0.4.0"
anyhow = "1.0.70"
log = "0.4.17"
regex = "1.8.1"
lazy_static = "1.4.0"
simple_logger = "4.1.0"
micromap = { version = "0.0.12", features = ["serde"] }
emap = {version = "0.0.8", features = ["serde"] }
nohash-hasher = "0.2.0"
libc = "0.2.141"
sxd-xpath = "0.4.2"
sxd-document = "0.3.2"
xml-builder = "0.5.2"
hex = "0.4.3"
ctor = "0.2.0"
itertools = "0.10.5"
bincode = "1.3.3"
serde = { version = "1.0.160", features = ["derive"] }
rstest = "0.16.0"
rustc-hash = "1.1.0"

[dev-dependencies]
fsutils = "0.1.7"
tempfile = "3.5.0"
predicates = "3.0.3"
