[package]
name = "sodg"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/objectionary/sodg"
description = "Simple Object DiGraph"
readme = "README.md"
license-file = "LICENSE.txt"
homepage = "https://github.com/objectionary/sodg"
keywords = ["graph", "oop"]
categories = ["data-structures", "memory-management"]

[dependencies]
anyhow = "1.0.66"
log = "0.4.17"
regex = "1.7.0"
lazy_static = "1.4.0"
simple_logger = "2.3.0"
sxd-xpath = "0.4.2"
sxd-document = "0.3.2"
xml-builder = "0.5.0"
hex = "0.4.3"
ctor = "0.1.26"
itertools = "0.10.5"
bincode = "1.3.3"
serde = { version = "1.0.145", features = ["derive"] }
rstest = "0.15.0"

[dev-dependencies]
fsutils = "0.1.7"
tempfile = "3.3.0"
predicates = "2.1.1"
clippy = "0.0.302"
