[package]
name = "sot"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/objectionary/sot"
description = "Simple Object Tree"
readme = "README.md"
license-file = "LICENSE.txt"
homepage = "https://github.com/objectionary/sot"
keywords = ["graph", "tree", "oop"]
categories = ["graph"]

[dependencies]
anyhow = "1.0.65"
log = "0.4.17"
regex = "1.6.0"
lazy_static = "1.4.0"
simple_logger = "2.3.0"
sxd-xpath = "0.4.2"
sxd-document = "0.3.2"
xml-builder = "0.5.0"
ctor = "0.1.23"
itertools = "0.10.5"
bincode = "1.3.3"
serde = { version = "1.0.145", features = ["derive"] }

[dev-dependencies]
fsutils = "0.1.7"
tempfile = "3.3.0"
predicates = "2.1.1"
