[package]
name = "sodg"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/objectionary/sodg"
description = "Surging Object DiGraph (SODG)"
readme = "README.md"
license-file = "LICENSE.txt"
homepage = "https://github.com/objectionary/sodg"
keywords = ["graph", "oop"]
categories = ["data-structures", "memory-management"]

[features]
sober = []
gc = []

[dependencies]
anyhow = "1.0.70"
log = "0.4.17"
regex = "1.7.1"
lazy_static = "1.4.0"
simple_logger = "4.0.0"
sxd-xpath = "0.4.2"
sxd-document = "0.3.2"
xml-builder = "0.5.1"
hex = "0.4.3"
ctor = "0.1.26"
itertools = "0.10.5"
bincode = "1.3.3"
serde = { version = "1.0.156", features = ["derive"] }
rstest = "0.16.0"

[dev-dependencies]
fsutils = "0.1.7"
tempfile = "3.4.0"
predicates = "3.0.1"
